import { IPersonVetting_Item } from '@models/INL.VettingService.Models/iperson-vetting_item';
import { IPersonVettingType_Item } from '@models/INL.VettingService.Models/iperson-vetting-type_item';
import { IPersonVettingHit_Item } from '@models/INL.VettingService.Models/iperson-vetting-hit_item';
import { IPersonVettingVettingType_Item } from '@models/INL.VettingService.Models/iperson-vetting-vetting-type_item';
import { VettingPersonsVetting } from '@models/vetting-persons-vetting';
import { ICourtesyBatch_Item } from '@models/INL.VettingService.Models/icourtesy-batch_item';

export class BatchRequestModel {
    public Ordinal: number = 0;
    public VettingBatchID: number = 0;
    public VettingBatchName: string = "";
    public VettingBatchNumber: number = 0;
    public VettingBatchOrdinal: number = 0;
    public TrainingEventID?: number;
    public CountryID?: number;
    public VettingBatchTypeID: number = 0;
    public VettingBatchType: string = "";
    public AssignedToAppUserID?: number;
    public NumberofParticipants?: number;
    public AssignedToAppUserFullName: string = "";
    public AssignedToAppUserFirstName: string = "";
    public AssignedToAppUserLastName: string = "";
    public VettingBatchStatusID?: number = 0;
    public VettingBatchStatus: string = "";
    public VettingBatchStatusDisplay: string = "";
    public HasBeenAccepted: boolean = this.VettingBatchStatusID != 1;
    public IsCorrectionRequired?: boolean = false;
    public CourtesyVettingOverrideFlag?: boolean;
    public CourtesyVettingOverrideReason: string = "";
    public GTTSTrackingNumber: string = "";
    public LeahyTrackingNumber: string = "";
    public INKTrackingNumber: string = "";
    public DateVettingResultsNeededBy?: Date;
    public DateSubmitted?: Date;
    public DateAccepted?: Date;
    public DateSentToCourtesy?: Date;
    public DateCourtesyCompleted?: Date;
    public DateSentToLeahy?: Date;
    public DateLeahyResultsReceived?: Date;
    public DateVettingResultsNotified?: Date;
    public EventStartDate?: Date;
    public DateLeahyFileGenerated?: Date;
    public VettingFundingSourceID: number = 0;
    public VettingFundingSource: string = "";
    public AuthorizingLawID: number = 0;
    public AuthorizingLaw: string = "";
    public VettingBatchNotes: string = "";
    public ModifiedByAppUserID: number = 0;
    public ModifiedDate: Date = new Date(0);
    public TrainingEventName: string = "";
    public TrainingEventBusinessUnitAcronym: string = "";
    public HasHits: boolean = false;
    public SubmittedAppUserName: string = "";
    public AcceptedAppUserName: string = "";
    public CourtesyCompleteAppUserName: string = "";
    public SentToCourtesyAppUserName: string = "";
    public SentToLeahyAppUserName: string = "";
    public FileID: number;
    public RequestPOC: string = "";
    public Comments: string = "";
    public CommentsDisabled: boolean = false;
    //public PersonVettings?: IPersonVetting_Item[];
    public PersonVettingTypes?: IPersonVettingType_Item[];
    public PersonVettingHits?: IPersonVettingHit_Item[];
    public IsSubmitResultEnabled?: boolean = false;
    public PersonVettingVettingTypes: IPersonVettingVettingType_Item[];
    public PersonVettings?: VettingPersonsVetting[];
    public ActionVisible?: boolean = false;
    public SubmitToLeahyEnabled: boolean = true;
    public NotifyResultsEnabled: boolean = true;
    public CourtesyBatch?: ICourtesyBatch_Item;
    public IsSubmitted?: boolean = false;
}
