-- USPartnerAgencies MERGE

MERGE INTO [unitlibrary].[USPartnerAgencies] TARGET
USING 
    (SELECT [Name], [Initials], [IsActive], [ModifiedByAppUserID]
       FROM (VALUES
                ('Federal Bureau of Investigation', 'FBI', 1, 1),
                ('Drug Enforcement Administration', 'DEA', 1, 1), 
                ('Homeland Security Investigations', 'HSI', 1, 1), 
                ('Office of Overseas Prosecutorial Development Assistance & Training', 'OPDAT', 1, 1), 
                ('International Criminal Investigative Training Assistance Program', 'ICITAP', 1, 1), 
                ('Alcohol, Tobacco, Firearms and Explosives', 'ATF', 1, 1), 
                ('ATA', 'ATA', 1, 1), 
                ('Customs and Border Patrol', 'CBP', 1, 1), 
                ('Department of Justice', 'DOJ', 1, 1), 
                ('United States Agency for International Development', 'USAID', 1, 1), 
                ('United States Marshals Service', 'U.S. Marshalls', 0, 1), 
                ('DAO', 'DAO', 1, 1), 
                ('Office of Defense Coordination', 'ODC', 1, 1), 
                ('International Law Enforcement Academy', 'ILEA', 1, 1), 
                ('United States Marshals Service', 'USMS', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs', 'INL', 1, 1), 
                ('ECC', 'ECC', 1, 1), 
                ('Export Control and Related Border Security', 'EXBS', 1, 1), 
                ('Export Control and Related Border Security - TDY Instructors', 'EXBS TDY Instructors', 1, 1), 
                ('Export Control and Related Border Security - TDY Advisors', 'EXBS TDY Advisors', 1, 1), 
                ('Export Control and Related Border Security - Mexico', 'EXBS Mexico', 1, 1), 
                ('Export Control and Related Border Security - Panama', 'EXBS Panama', 1, 1), 
                ('Export Control and Related Border Security - Regional', 'EXBS Regional', 1, 1), 
                ('Department of Homeland Security', 'DHS', 1, 1), 
                ('Department of Commerce', 'DOC', 1, 1), 
                ('Department of Energy', 'DOE', 1, 1), 
                ('Department of Defense', 'DOD', 1, 1), 
                ('Fraud Prevention Unit', 'FPU', 1, 1), 
                ('Organization of American States', 'OAS', 1, 1), 
                ('OAS Inter-American Committee against Terrorism', 'OAS/CICTE', 1, 1), 
                ('Global Initiative to Combat Nuclear Terrorism', 'GICNT', 1, 1), 
                ('University of Georgia Center for International Trade and Security', 'UGA CITS', 1, 1), 
                ('LATA', 'LATA', 1, 1), 
                ('SECURUS', 'SECURUS', 1, 1), 
                ('Wisconsin Project', 'Wisconsin Poject', 1, 1), 
                ('United Nations', 'UN', 1, 1), 
                ('United Nations Office on Drugs and Crime', 'UNODC', 1, 1), 
                ('World Customs Organization', 'WCO', 1, 1), 
                ('SEGMAN', 'SEGMAN', 1, 1), 
                ('European Union', 'EU', 1, 1), 
                ('Panama', 'Panama', 0, 1), 
                ('Canada', 'Canada', 0, 1), 
                ('Spain', 'Spain', 0, 1), 
                ('Contractor', 'Contractor', 1, 1), 
                ('Grantee', 'Grantee', 1, 1), 
                ('CCIPS', 'CCIPS', 1, 1), 
                ('Department of State', 'DOS', 1, 1), 
                ('Office of Foreign Assets Control', 'OFAC', 1, 1),           
                ('Colombo Plan', '', 1, 1),
                ('Escuela de antisecuestro y antiextorsión', 'ESANT', 1, 1), 
                ('Escuela de aviación policial', 'ESAVI', 1, 1), 
                ('Escuela de cadetes de policía general Francisco de Paula Santander', 'ECSAN', 1, 1), 
                ('Escuela de Carabineros "Eduardo Cuevas García"', 'ESECU', 1, 1), 
                ('Escuela de Carabineros "Rafael Núñez" ', 'ESRAN', 1, 1), 
                ('Escuela de guías y adiestramiento canino ', 'ESGAC', 1, 1), 
                ('Escuela de inteligencia y contrainteligencia ', 'ESCIC', 1, 1), 
                ('Escuela de investigación criminal ', 'ESINC', 1, 1), 
                ('Escuela de Policía "Antonio Nariño"', 'ESANA', 1, 1), 
                ('Escuela de Policía "Carlos Eugenio Restrepo"', 'ESCER', 1, 1), 
                ('Escuela de Policía "Gabriel González"', 'ESGON', 1, 1), 
                ('Escuela de policía "Rafael Reyes"', 'ESREY', 1, 1), 
                ('Escuela de Policía "Simón Bolívar"', 'ESBOL', 1, 1), 
                ('Escuela de Policía de Yuto "Miguel Antonio Caicedo Mena"', 'ESMAC', 1, 1), 
                ('Escuela de policía en protección y seguridad', 'ESPRO', 1, 1), 
                ('Escuela de Policía Provincia de Sumapaz ', 'ESSUM', 1, 1), 
                ('Escuela de Poligrafia, Policia Nacional', 'EPPN', 1, 1), 
                ('Escuela de posgrados de policía ', 'ESPOL', 1, 1), 
                ('Escuela de seguridad vial ', 'ESAVI', 1, 1), 
                ('Escuela de suboficiales y nivel ejecutivo Gonzalo Jimenez de Quesada', 'ESJIM', 1, 1), 
                ('Escuela de telemática y electrónica', 'ESTIC', 1, 1), 
                ('Escuela internacional del uso de la fuerza polical para la paz', 'CENOP', 1, 1), 
                ('Escuela metropolitana de bogotá', 'ESMEB', 1, 1), 
                ('Escuela Nacional de Carabineros ', 'ESCAR', 1, 1), 
                ('Escuela regional de la comunidad americana de la inteligencia antidrogas', 'ERCAIAD', 1, 1), 
                ('Fort Eustis, Virginia, USA', 'FT-EUSTIS', 1, 1), 
                ('Fort Indiantown, Pennsylvania, USA', 'FT-INDIANTOWN', 1, 1), 
                ('Fort Rucker, Alabama, USA', 'FT-RUCKER', 1, 1), 
                ('Inter-American Air Forces Academy ', 'IAAFA', 1, 1), 
                ('Inter-American Drug Abuse Control Commision', 'OAS/CICAD', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Belize', 'INL-BELIZE', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Colombia', 'INL-COLOMBIA', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Costa Rica', 'INL-COSTARICA', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Dominican Republic', 'INL-DOMREPUBLIC', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - El Salvador', 'INL-ELSALVADOR', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Guatemala', 'INL-GUATEMALA', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Honduras', 'INL-HONDURAS', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Mexico', 'INL-MEXICO', 1, 1), 
                ('International Narcotics and Law Enforcement Affairs - Peru', 'INL-PERU', 1, 1), 
                ('International Organization for Migration', 'IOM', 1, 1), 
                ('Miami Dade Police Department', 'MDPD', 1, 1), 
                ('National Association of Drug Court Professionals', 'NADCP', 1, 1), 
                ('Naval Small Craft Instruction and Technical Training School', 'NAVSCIATTS', 1, 1), 
                ('Western Hemisphere Institute for Security Cooperation', 'WHINSEC', 1, 1)  
            ) X ([Name], [Initials], [IsActive], [ModifiedByAppUserID])
    ) AS source ([Name], [Initials], [IsActive], [ModifiedByAppUserID])
ON (target.[Name] = source.[Name] AND target.[Initials] = source.[Initials])
WHEN NOT MATCHED BY TARGET THEN 
    INSERT ([Name], [Initials], [IsActive], [ModifiedByAppUserID])
    VALUES ([Name], [Initials], [IsActive], [ModifiedByAppUserID]);