/*
    **************************************************************************
    PostNotificationsConfiguration.sql
    **************************************************************************    
*/ 
CREATE TABLE [messaging].[PostNotificationsConfiguration]
(
    [PostID] INT NOT NULL, 
    [CloseOutNotificationsTime] INT NOT NULL DEFAULT 5, 
	[ModifiedByAppUserID] INT NOT NULL,
	[ModifiedDate] DATETIME NOT NULL DEFAULT (getutcdate()),
	[SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL DEFAULT (sysutcdatetime()),
	[SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime]), 
    CONSTRAINT [PK_PostNotificationsConfiguration] 
		PRIMARY KEY ([PostID]), 
    CONSTRAINT [FK_PostNotificationsConfiguration_Posts] 
		FOREIGN KEY ([PostID]) 
		REFERENCES [location].[Posts]([PostID]),
    CONSTRAINT [FK_PostNotificationsConfiguration_AppUsers] 
        FOREIGN KEY ([ModifiedByAppUserID]) 
        REFERENCES [users].[AppUsers]([AppUserID])   
)
ON [PRIMARY]
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [messaging].[PostNotificationsConfiguration_History]))
GO

/*  Table description  */
EXECUTE sp_addextendedproperty @name = N'MS_Description', 
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
	@value = N'A table to save post-specific messaging/notifications configuration information.'
GO

/*  Primary Key (PostID) description  */
EXEC sp_addextendedproperty @name = N'MS_Description',
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
    @level2type = N'COLUMN', @level2name = N'PostID',
	@value = N'The Primary key for this table.  Foreign key pointing to the locations.Posts table.'
GO

/*  CloseOutNotificationsTime column  */
EXEC sp_addextendedproperty @name = N'MS_Description',
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
    @level2type = N'COLUMN', @level2name = N'CloseOutNotificationsTime',
	@value = N'The post''s required time past an event end date before a notification to close the event is generated by the system and sent to the Training Event Organizer/PM.'
GO

/*  ModifiedByAppUserID column description  */
EXEC sys.sp_addextendedproperty @name = N'MS_Description',
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
	@level2type = N'COLUMN', @level2name = N'ModifiedByAppUserID',
	@value = N'Identifies the user who created or updated the record.  Foreign key pointing to the Users table.'
GO

/*  ModifiedDate column description  */
EXEC sys.sp_addextendedproperty @name = N'MS_Description',
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
	@level2type = N'COLUMN', @level2name = N'ModifiedDate',
	@value = N'Date/Time when the record was modified or created.  Normally would be in sync with SysStartTime.  Used by the application to track changes regardless if the table is temporalized or not.'
GO

/*  SysStartTime column description  */
EXEC sys.sp_addextendedproperty @name = N'MS_Description',
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
	@level2type = N'COLUMN', @level2name = N'SysStartTime',
	@value = N'System Date/Time when the record was created.  Used to denote the start of the timeperiod for which the record is valid.'
GO

/*  SysEndTime column description  */
EXEC sys.sp_addextendedproperty @name = N'MS_Description',
	@level0type = N'SCHEMA', @level0name = N'messaging',
	@level1type = N'TABLE',  @level1name = N'PostNotificationsConfiguration',
	@level2type = N'COLUMN', @level2name = N'SysEndTime',
	@value = N'System Date/Time when the record was updated.  Used to denote the end of the timeperiod for which the record is valid.'
GO