/*  Turn IDENTITY_INSERT ON    */
SET IDENTITY_INSERT [location].[Languages] ON
GO

IF (NOT EXISTS(SELECT * FROM [location].[Languages]))
	BEGIN
		/*  INSERT VALUES into the table    */
		INSERT INTO [location].[Languages]
				([LanguageID]
				,[Code]
				,[Description]
				,[ModifiedByAppUserID])
			VALUES            
                (1, N'AF', N'Afghan Familiarization', 1),
                (2, N'AA', N'Afrikaans', 1),
                (3, N'FB', N'Akan Twi', 1),
                (4, N'BC', N'Akposso', 1),
                (5, N'AB', N'Albanian', 1),
                (6, N'CR', N'Amashi', 1),
                (7, N'AC', N'Amharic', 1),
                (8, N'AD', N'Arabic', 1),
                (9, N'AE', N'Arabic (Egyptian)', 1),
                (10, N'AI', N'Arabic (Iraqi)', 1),
                (11, N'AN', N'Arabic (Saudi)', 1),
                (12, N'AZ', N'Arabic (Spec.Dialect)', 1),
                (13, N'AP', N'Arabic (Syrian)', 1),
                (14, N'QW', N'Arabic (Western)', 1),
                (15, N'QE', N'Arabic Pen (Eastern)', 1),
                (16, N'DG', N'Arabic-Gulf', 1),
                (17, N'RE', N'Armenian (Eastern)', 1),
                (18, N'RW', N'Armenian (Western)', 1),
                (19, N'AS', N'Assamese', 1),
                (20, N'AY', N'Aymara', 1),
                (21, N'AX', N'Azerbaijani', 1),
                (22, N'BK', N'Bakweri', 1),
                (23, N'BT', N'Balochi', 1),
                (24, N'BJ', N'Bamileke', 1),
                (25, N'BQ', N'Basque', 1),
                (26, N'EC', N'Bassa (Cameroons)', 1),
                (27, N'BH', N'Baule', 1),
                (28, N'BE', N'Beja', 1),
                (29, N'BM', N'Bemba/Cibemba', 1),
                (30, N'BN', N'Bengali', 1),
                (31, N'BR', N'Berber', 1),
                (32, N'CU', N'Bini', 1),
                (33, N'BX', N'Bosnian', 1),
                (34, N'ED', N'Bubi', 1),
                (35, N'BU', N'Bulgarian', 1),
                (36, N'BY', N'Burmese', 1),
                (37, N'BL', N'Byelorussian', 1),
                (38, N'CA', N'Cambodian/Khmer', 1),
                (39, N'CB', N'Catalan', 1),
                (40, N'VB', N'Cebuano', 1),
                (41, N'CJ', N'Chamorro', 1),
                (42, N'HV', N'Chavacano', 1),
                (43, N'CK', N'Chechen', 1),
                (44, N'YD', N'Chinese (Amoy)', 1),
                (45, N'CC', N'Chinese (Cantonese)', 1),
                (46, N'CQ', N'Chinese (Fuchow)', 1),
                (47, N'CH', N'Chinese (Hakka)', 1),
                (48, N'CM', N'Chinese (Mandarin)', 1),
                (49, N'YE', N'Chinese (Swatow)', 1),
                (50, N'CS', N'Chinese Wu', 1),
                (51, N'NY', N'Chinyanja/Nyanja/Chichewa', 1),
                (52, N'CY', N'Chokwe', 1),
                (53, N'HR', N'Croatian', 1),
                (54, N'CX', N'Czech', 1),
                (55, N'DA', N'Danish', 1),
                (56, N'DB', N'Djerma/Songhai', 1),
                (57, N'DL', N'Duala', 1),
                (58, N'DU', N'Dutch/Flemish', 1),
                (59, N'DW', N'Dutch-Creole', 1),
                (60, N'EF', N'Efik', 1),
                (61, N'EN', N'English', 1),
                (62, N'ES', N'Estonian', 1),
                (63, N'EW', N'Ewe', 1),
                (64, N'EX', N'Ewondo', 1),
                (65, N'GX', N'Fanagalo', 1),
                (66, N'FA', N'Fang/Bulu', 1),
                (67, N'FG', N'Fijian', 1),
                (68, N'FJ', N'Finnish', 1),
                (69, N'FQ', N'Fon', 1),
                (70, N'FM', N'Formosan', 1),
                (71, N'FR', N'French', 1),
                (72, N'FV', N'Fula/Toucouleur', 1),
                (73, N'GB', N'Ga', 1),
                (74, N'GL', N'Gaelic/Irish Gaelic', 1),
                (75, N'GA', N'Galla', 1),
                (76, N'GG', N'Georgian', 1),
                (77, N'GM', N'German', 1),
                (78, N'GS', N'German (Swiss)', 1),
                (79, N'GR', N'Greek', 1),
                (80, N'GU', N'Guarani', 1),
                (81, N'GW', N'Gujarati', 1),
                (82, N'HC', N'Haitian Creole', 1),
                (83, N'HD', N'Hassaniya', 1),
                (84, N'HS', N'Hausa', 1),
                (85, N'HE', N'Hebrew', 1),
                (86, N'HJ', N'Hindi', 1),
                (87, N'HM', N'Hmong', 1),
                (88, N'HU', N'Hungarian', 1),
                (89, N'JD', N'Iban', 1),
                (90, N'JC', N'Icelandic', 1),
                (91, N'JB', N'Igbo', 1),
                (92, N'JF', N'Ila-Tonga', 1),
                (93, N'JL', N'Ilocano', 1),
                (94, N'JN', N'Indonesian', 1),
                (95, N'JT', N'Italian', 1),
                (96, N'JP', N'Jamaican Patois', 1),
                (97, N'JA', N'Japanese', 1),
                (98, N'JV', N'Javanese', 1),
                (99, N'KT', N'Kabre', 1),
                (100, N'KA', N'Kannada', 1),
                (101, N'JH', N'Kanouri', 1),
                (102, N'GP', N'Kapingamarangi', 1),
                (103, N'KB', N'Kashmiri', 1),
                (104, N'KE', N'Kazakh', 1),
                (105, N'KG', N'Kikongo/Kongo', 1),
                (106, N'KJ', N'Kikuyu', 1),
                (107, N'KK', N'Kimbundu', 1),
                (108, N'KL', N'Kinyarwanda/Rwanda', 1),
                (109, N'RN', N'Kirindi/Rundi', 1),
                (110, N'KS', N'Kissi', 1),
                (111, N'TG', N'Ki-Taki', 1),
                (112, N'KN', N'Kituba/Munukutuba', 1),
                (113, N'JJ', N'Kjaw', 1),
                (114, N'KP', N'Korean', 1),
                (115, N'KV', N'Kpelle', 1),
                (116, N'KW', N'Krio', 1),
                (117, N'BG', N'Kru', 1),
                (118, N'EB', N'Kumbo', 1),
                (119, N'KU', N'Kurdish', 1),
                (120, N'XK', N'Kurdish (Kurmanji)', 1),
                (121, N'XS', N'Kurdish/Sorani', 1),
                (122, N'QR', N'Kusaie', 1),
                (123, N'KM', N'Kyrgyz', 1),
                (124, N'LL', N'Lamba', 1),
                (125, N'YZ', N'Language (Other)', 1),
                (126, N'LC', N'Lao', 1),
                (127, N'LT', N'Latin', 1),
                (128, N'LE', N'Latvian', 1),
                (129, N'LJ', N'Lingala', 1),
                (130, N'LT', N'Lithuanian', 1),
                (131, N'LV', N'Loma', 1),
                (132, N'LK', N'Luba (Kasai)', 1),
                (133, N'LS', N'Luganda/Ganda', 1),
                (134, N'LM', N'Lunda', 1),
                (135, N'LU', N'Luo', 1),
                (136, N'MA', N'Macedonian', 1),
                (137, N'MG', N'Malagasy', 1),
                (138, N'ML', N'Malay', 1),
                (139, N'MN', N'Malayalam', 1),
                (140, N'MP', N'Maltese', 1),
                (141, N'BA', N'Mandingo-Bambara', 1),
                (142, N'MQ', N'Mandingo-Malinke-Dio', 1),
                (143, N'MR', N'Marathi', 1),
                (144, N'MM', N'Marshallese', 1),
                (145, N'MS', N'Masai', 1),
                (146, N'EE', N'Mauritius Creole', 1),
                (147, N'MF', N'Maya', 1),
                (148, N'MT', N'Mende', 1),
                (149, N'MO', N'Moldovan', 1),
                (150, N'MV', N'Mongolian', 1),
                (151, N'ME', N'Montenegrin', 1),
                (152, N'MY', N'More', 1),
                (153, N'RL', N'Morth Lockese', 1),
                (154, N'DD', N'Mpongwe', 1),
                (155, N'ND', N'Ndebele', 1),
                (156, N'NE', N'Nepali/Nepalese', 1),
                (157, N'NR', N'Norwegian', 1),
                (158, N'NV', N'Nubian', 1),
                (159, N'ST', N'Nyamwezi/Sukuma', 1),
                (160, N'QA', N'Oriya', 1),
                (161, N'PJ', N'Panjabi/Punjabi', 1),
                (162, N'PA', N'Papiamento', 1),
                (163, N'PV', N'Pashto (Afghan)', 1),
                (164, N'PW', N'Pashto (Pakistani)', 1),
                (165, N'PU', N'Pashto/Pushtu', 1),
                (166, N'PD', N'Paulauan', 1),
                (167, N'TB', N'Persian (Tajiki)', 1),
                (168, N'PG', N'Persian/Afghan/Dari', 1),
                (169, N'PF', N'Persian/Farsi/Iranian', 1),
                (170, N'WS', N'Pidgin/Wescos', 1),
                (171, N'TA', N'Pilipino/Tagalog', 1),
                (172, N'PS', N'Pizar Malay', 1),
                (173, N'PL', N'Polish', 1),
                (174, N'PC', N'Ponapean', 1),
                (175, N'PT', N'Portuguese', 1),
                (176, N'PQ', N'Portuguese', 1),
                (177, N'PY', N'Portuguese', 1),
                (178, N'PX', N'Pulap', 1),
                (179, N'QU', N'Quechua', 1),
                (180, N'RQ', N'Romanian', 1),
                (181, N'RU', N'Russian', 1),
                (182, N'RY', N'Ryukyuan/Okinawan', 1),
                (183, N'SB', N'Sango', 1),
                (184, N'RG', N'Sanskrit ', 1),
                (185, N'SE', N'Sara', 1),
                (186, N'SR', N'Serbian', 1),
                (187, N'SC', N'Serbo-Croatian', 1),
                (188, N'SV', N'Serer', 1),
                (189, N'SH', N'Shona', 1),
                (190, N'SD', N'Sindhi', 1),
                (191, N'SJ', N'Singhalese/Sinhala', 1),
                (192, N'SK', N'Slovak', 1),
                (193, N'SL', N'Slovenian', 1),
                (194, N'SM', N'Somali', 1),
                (195, N'SN', N'Sonike', 1),
                (196, N'SO', N'Sorani', 1),
                (197, N'SP', N'Sotho/Sesutho', 1),
                (198, N'QB', N'Spanish', 1),
                (199, N'SU', N'Susu', 1),
                (200, N'SW', N'Swahili/Kiswahili', 1),
                (201, N'SX', N'Swati/Siswati', 1),
                (202, N'SY', N'Swedish', 1),
                (203, N'TC', N'Tamil', 1),
                (204, N'TM', N'Tatar', 1),
                (205, N'TE', N'Telugu', 1),
                (206, N'TF', N'Temne', 1),
                (207, N'TT', N'Tetun', 1),
                (208, N'TH', N'Thai', 1),
                (209, N'TJ', N'Tibetan', 1),
                (210, N'TN', N'Tigre', 1),
                (211, N'TL', N'Tigrinya', 1),
                (212, N'TO', N'Tok Pisin', 1),
                (213, N'TQ', N'Trukese', 1),
                (214, N'TR', N'Tshwa/Tswa', 1),
                (215, N'TP', N'Tsonga', 1),
                (216, N'TS', N'Tswana/Setswana', 1),
                (217, N'UC', N'Tumbuka', 1),
                (218, N'TU', N'Turkish', 1),
                (219, N'UB', N'Turkmen', 1),
                (220, N'UJ', N'Uighur', 1),
                (221, N'UK', N'Ukrainian', 1),
                (222, N'UL', N'Ulithi', 1),
                (223, N'UM', N'Umbundu', 1),
                (224, N'UR', N'Urdu', 1),
                (225, N'UX', N'Uzbek', 1),
                (226, N'VA', N'Vai', 1),
                (227, N'VS', N'Vietnamese', 1),
                (228, N'VY', N'Visayan/Cebuano', 1),
                (229, N'WE', N'Welsh', 1),
                (230, N'WL', N'Woleai', 1),
                (231, N'WQ', N'Wolof', 1),
                (232, N'WH', N'Xhosa', 1),
                (233, N'YA', N'Yakut', 1),
                (234, N'YB', N'Yao(Malawi&Mozamb)', 1),
                (235, N'YP', N'Yappese', 1),
                (236, N'YJ', N'Yiddish', 1),
                (237, N'YQ', N'Yoruba', 1),
                (238, N'XU', N'Zulu', 1)
	END
GO

/*  Turn IDENTITY_INSERT OFF    */
SET IDENTITY_INSERT [location].[Languages] OFF
GO

/*  Set new INDENTIY Starting VALUE */
DBCC CHECKIDENT ('[location].[Languages]', RESEED)
GO