/*
    In order to maintain backwards compatibility with migrated data from TTS,
    we need to set the IDENTITY_INSERT property of the table ON before running
	the INSERT statement.  Afterwards, we set the IDENTITY_INSERT property to OFF,
	and set the seed value to the highest IDENTITY value.
*/

/*  Turn IDENTITY_INSERT ON    */
SET IDENTITY_INSERT [location].[Missions] ON
GO

IF (NOT EXISTS(SELECT * FROM [location].[Missions]))
	BEGIN
		/*  INSERT VALUES into the table    */
        INSERT INTO [location].[Missions] 
                ([MissionID]
                ,[MissionCode]
                ,[Name]
                ,[FullName]
                ,[MissionTypeID]
                ,[IsActive]
                ,[ModifiedByAppUserID])               
        VALUES (10001, N'AFG', N'Afghanistan', N'U.S. Mission to Afghanistan', 1, 1, 1),
               (10002, N'USAU', N'USAU', N'U.S. Mission to the African Union (USAU)', 2, 1, 1),
               (10003, N'ALB', N'Albania', N'U.S. Mission to Albania', 1, 1, 1),
               (10004, N'DZA', N'Algeria', N'U.S. Mission to Algeria', 1, 1, 1),
               (10005, N'AGO', N'Angola', N'U.S. Mission to Angola', 1, 1, 1),
               (10006, N'ARG', N'Argentina', N'U.S. Mission to Argentina', 1, 1, 1),
               (10007, N'ARM', N'Armenia', N'U.S. Mission to Armenia', 1, 1, 1),
               (10008, N'AUS', N'Australia', N'U.S. Mission to Australia', 1, 1, 1),
               (10009, N'AUT', N'Austria', N'U.S. Mission to Austria', 1, 1, 1),
               (10010, N'AZE', N'Azerbaijan', N'U.S. Mission to Azerbaijan', 1, 1, 1),
               (10011, N'BHS', N'Bahamas, The', N'U.S. Mission to the Bahamas', 1, 1, 1),
               (10012, N'BHR', N'Bahrain', N'U.S. Mission to Bahrain', 1, 1, 1),
               (10013, N'BGD', N'Bangladesh', N'U.S. Mission to Bangladesh', 1, 1, 1),
               (10014, N'BRB', N'Barbados & Eastern Caribbean', N'U.S. Mission to Barbados and the Eastern Caribbean', 1, 1, 1),
               (10015, N'BLR', N'Belarus', N'U.S. Mission to Belarus', 1, 1, 1),
               (10016, N'BEL', N'Belgium', N'U.S. Mission to Belgium', 1, 1, 1),
               (10017, N'BLZ', N'Belize', N'U.S. Mission to Belize', 1, 1, 1),
               (10018, N'BEN', N'Benin', N'U.S. Mission to Benin', 1, 1, 1),
               (10019, N'BOL', N'Bolivia', N'U.S. Mission to Bolivia', 1, 1, 1),
               (10020, N'BIH', N'Bosnia and Herzegovina', N'U.S. Mission to Bosnia and Herzegovina', 1, 1, 1),
               (10021, N'BWA', N'Botswana', N'U.S. Mission to Botswana', 1, 1, 1),
               (10022, N'BRA', N'Brazil', N'U.S. Mission to Brazil', 1, 1, 1),
               (10023, N'BRN', N'Brunei', N'U.S. Mission to Brunei', 1, 1, 1),
               (10024, N'BGR', N'Bulgaria', N'U.S. Mission to Bulgaria', 1, 1, 1),
               (10025, N'BFA', N'Burkina Faso', N'U.S. Mission to Burkina Faso', 1, 1, 1),
               (10026, N'MMR', N'Burma', N'U.S. Mission to Burma', 1, 1, 1),
               (10027, N'BDI', N'Burundi', N'U.S. Mission to Burundi', 1, 1, 1),
               (10028, N'KHM', N'Cambodia', N'U.S. Mission to Cambodia', 1, 1, 1),
               (10029, N'CMR', N'Cameroon', N'U.S. Mission to Cameroon', 1, 1, 1),
               (10030, N'CAN', N'Canada', N'U.S. Mission to Canada', 1, 1, 1),
               (10031, N'CPV', N'Cabo Verde', N'U.S. Mission to Cabo Verde', 1, 1, 1),
               (10032, N'CAF', N'Central African Republic', N'U.S. Mission to the Central African Republic', 1, 1, 1),
               (10033, N'TCD', N'Chad', N'U.S. Mission to Chad', 1, 1, 1),
               (10034, N'CHL', N'Chile', N'U.S. Mission to Chile', 1, 1, 1),
               (10035, N'CHN', N'China', N'U.S. Mission to China', 1, 1, 1),
               (10036, N'COL', N'Colombia', N'U.S. Mission to Colombia', 1, 1, 1),
               (10037, N'COG', N'Congo (Brazzaville)', N'U.S. Mission to the Republic of the Congo (Brazzaville)', 1, 1, 1),
               (10038, N'COD', N'Congo (Kinshasa)', N'U.S. Mission to the Democratic Republic of the Congo (Kinshasa)', 1, 1, 1),
               (10039, N'CRI', N'Costa Rica', N'U.S. Mission to Costa Rica', 1, 1, 1),
               (10040, N'CIV', N'Cote d''Ivoire', N'U.S. Mission to Cote d''Ivoire', 1, 1, 1),
               (10041, N'HRV', N'Croatia', N'U.S. Mission to Croatia', 1, 1, 1),
               (10042, N'CUB', N'Cuba', N'U.S. Mission to Cuba', 1, 1, 1),
               (10043, N'CYP', N'Cyprus', N'U.S. Mission to Cyprus', 1, 1, 1),
               (10044, N'CZE', N'Czech Republic', N'U.S. Mission to the Czech Republic', 1, 1, 1),
               (10045, N'DNK', N'Denmark', N'U.S. Mission to Denmark', 1, 1, 1),
               (10046, N'DJI', N'Djibouti', N'U.S. Mission to Djibouti', 1, 1, 1),
               (10047, N'DOM', N'Dominican Republic', N'U.S. Mission to the Dominican Republic', 1, 1, 1),
               (10048, N'ECU', N'Ecuador', N'U.S. Mission to Ecuador', 1, 1, 1),
               (10049, N'EGY', N'Egypt', N'U.S. Mission to Egypt', 1, 1, 1),
               (10050, N'SLV', N'El Salvador', N'U.S. Mission to El Salvador', 1, 1, 1),
               (10051, N'GNQ', N'Equatorial Guinea', N'U.S. Mission to Equatorial Guinea', 1, 1, 1),
               (10052, N'ERI', N'Eritrea', N'U.S. Mission to Eritrea', 1, 1, 1),
               (10053, N'EST', N'Estonia', N'U.S. Mission to Estonia', 1, 1, 1),
               (10054, N'ETH', N'Ethiopia', N'U.S. Mission to Ethiopia', 1, 1, 1),
               (10055, N'USEU', N'USEU', N'U.S. Mission to the European Union (USEU)', 2, 1, 1),
               (10056, N'FJI', N'Fiji, Kiribati, Nauru, Tonga & Tuvalu', N'U.S. Mission to Fiji, Kiribati, Nauru, Tonga, and Tuvalu', 1, 1, 1),
               (10057, N'FIN', N'Finland', N'U.S. Mission to Finland', 1, 1, 1),
               (10058, N'FRA', N'France & Monaco', N'U.S. Mission to France and Monaco', 1, 1, 1),
               (10059, N'GAB', N'Gabon & Sao Tome & Principe', N'U.S. Mission to Gabon and Sao Tome and Principe', 1, 1, 1),
               (10060, N'GMB', N'Gambia, The', N'U.S. Mission to The Gambia', 1, 1, 1),
               (10061, N'GEO', N'Georgia', N'U.S. Mission to Georgia', 1, 1, 1),
               (10062, N'DEU', N'Germany', N'U.S. Mission to Germany', 1, 1, 1),
               (10063, N'GHA', N'Ghana', N'U.S. Mission to Ghana', 1, 1, 1),
               (10064, N'GRC', N'Greece', N'U.S. Mission to Greece', 1, 1, 1),
               (10065, N'GTM', N'Guatemala', N'U.S. Mission to Guatemala', 1, 1, 1),
               (10066, N'GIN', N'Guinea', N'U.S. Mission to Guinea', 1, 1, 1),
               (10067, N'GUY', N'Guyana', N'U.S. Mission to Guyana', 1, 1, 1),
               (10068, N'HTI', N'Haiti', N'U.S. Mission to Haiti', 1, 1, 1),
               (10069, N'HND', N'Honduras', N'U.S. Mission to Honduras', 1, 1, 1),
               (10070, N'HKG', N'Hong Kong & Macau', N'U.S. Mission to Hong Kong and Macau', 1, 1, 1),
               (10071, N'HUN', N'Hungary', N'U.S. Mission to Hungary', 1, 1, 1),
               (10072, N'ISL', N'Iceland', N'U.S. Mission to Iceland', 1, 1, 1),
               (10073, N'IND', N'India', N'U.S. Mission to India and Bhutan', 1, 1, 1),
               (10074, N'IDN', N'Indonesia', N'U.S. Mission to Indonesia', 1, 1, 1),
               (10075, N'IRQ', N'Iraq', N'U.S. Mission to Iraq', 1, 1, 1),
               (10076, N'IRL', N'Ireland', N'U.S. Mission to Ireland', 1, 1, 1),
               (10077, N'ISR', N'Israel', N'U.S. Mission to Israel', 1, 1, 1),
               (10078, N'ITA', N'Italy & San Marino', N'U.S. Mission to Italy and San Marino', 1, 1, 1),
               (10079, N'JAM', N'Jamaica', N'U.S. Mission to Jamaica', 1, 1, 1),
               (10080, N'JPN', N'Japan', N'U.S. Mission to Japan', 1, 1, 1),
               (10081, N'JRU', N'Jerusalem', N'U.S. Mission to Jerusalem', 1, 1, 1),
               (10082, N'JOR', N'Jordan', N'U.S. Mission to Jordan', 1, 1, 1),
               (10083, N'KAZ', N'Kazakhstan', N'U.S. Mission to Kazakhstan', 1, 1, 1),
               (10084, N'KEN', N'Kenya', N'U.S. Mission to Kenya', 1, 1, 1),
               (10085, N'KOR', N'Korea, South', N'U.S. Mission to Korea', 1, 1, 1),
               (10086, N'KOS', N'Kosovo', N'U.S. Mission to Kosovo', 1, 1, 1),
               (10087, N'KWT', N'Kuwait', N'U.S. Mission to Kuwait', 1, 1, 1),
               (10088, N'KGZ', N'Kyrgyzstan', N'U.S. Mission to the Kyrgyz Republic', 1, 1, 1),
               (10089, N'LAO', N'Laos', N'U.S. Mission to Laos', 1, 1, 1),
               (10090, N'LVA', N'Latvia', N'U.S. Mission to Latvia', 1, 1, 1),
               (10091, N'LBN', N'Lebanon', N'U.S. Mission to Lebanon', 1, 1, 1),
               (10092, N'LSO', N'Lesotho', N'U.S. Mission to Lesotho', 1, 1, 1),
               (10093, N'LBR', N'Liberia', N'U.S. Mission to Liberia', 1, 1, 1),
               (10094, N'LBY', N'Libya', N'U.S. Mission to Libya', 1, 1, 1),
               (10095, N'LTU', N'Lithuania', N'U.S. Mission to Lithuania', 1, 1, 1),
               (10096, N'LUX', N'Luxembourg', N'U.S. Mission to Luxembourg', 1, 1, 1),
               (10097, N'MKD', N'Macedonia', N'U.S. Mission to Macedonia', 1, 1, 1),
               (10098, N'MDG', N'Madagascar & Comoros', N'U.S. Mission to Madagascar and the Comoros', 1, 1, 1),
               (10099, N'MWI', N'Malawi', N'U.S. Mission to Malawi', 1, 1, 1),
               (10100, N'MYS', N'Malaysia', N'U.S. Mission to Malaysia', 1, 1, 1),
               (10101, N'MLI', N'Mali', N'U.S. Mission to Mali', 1, 1, 1),
               (10102, N'MLT', N'Malta', N'U.S. Mission to Malta', 1, 1, 1),
               (10103, N'MHL', N'Marshall Islands', N'U.S. Mission to the Marshall Islands', 1, 1, 1),
               (10104, N'MRT', N'Mauritania', N'U.S. Mission to Mauritania', 1, 1, 1),
               (10105, N'MUS', N'Mauritius & Seychelles', N'U.S. Mission to Mauritius and Seychelles', 1, 1, 1),
               (10106, N'MEX', N'Mexico', N'U.S. Mission to Mexico', 1, 1, 1),
               (10107, N'FSM', N'Micronesia', N'U.S. Mission to Micronesia', 1, 1, 1),
               (10108, N'MDA', N'Moldova', N'U.S. Mission to Moldova', 1, 1, 1),
               (10109, N'MNG', N'Mongolia', N'U.S. Mission to Mongolia', 1, 1, 1),
               (10110, N'MNE', N'Montenegro', N'U.S. Mission to Montenegro', 1, 1, 1),
               (10111, N'MAR', N'Morocco', N'U.S. Mission to Morocco', 1, 1, 1),
               (10112, N'MOZ', N'Mozambique', N'U.S. Mission to Mozambique', 1, 1, 1),
               (10113, N'NAM', N'Namibia', N'U.S. Mission to Namibia', 1, 1, 1),
               (10114, N'NPL', N'Nepal', N'U.S. Mission to Nepal', 1, 1, 1),
               (10115, N'NLD', N'Netherlands', N'U.S. Mission to Netherlands', 1, 1, 1),
               (10116, N'NZL', N'New Zealand & Samoa', N'U.S. Mission to New Zealand and Samoa', 1, 1, 1),
               (10117, N'NIC', N'Nicaragua', N'U.S. Mission to Nicaragua', 1, 1, 1),
               (10118, N'NER', N'Niger', N'U.S. Mission to Niger', 1, 1, 1),
               (10119, N'NGA', N'Nigeria', N'U.S. Mission to Nigeria', 1, 1, 1),
               (10121, N'NATO', N'USNATO', N'U.S. Mission to the North Atlantic Treaty Organization (USNATO)', 2, 1, 1),
               (10123, N'NOR', N'Norway', N'U.S. Mission to Norway', 1, 1, 1),
               (10124, N'OMN', N'Oman', N'U.S. Mission to Oman', 1, 1, 1),
               (10125, N'OECD', N'USOECD', N'U.S. Mission to the Organization for Economic Cooperation and Development (USOECD)', 2, 1, 1),
               (10126, N'OSCE', N'USOSCE', N'U.S. Mission to the Organization for Security and Cooperation in Europe (USOSCE)', 2, 1, 1),
               (10127, N'PAK', N'Pakistan', N'U.S. Mission to Pakistan', 1, 1, 1),
               (10128, N'PLW', N'Palau', N'U.S. Mission to Palau', 1, 1, 1),
               (10129, N'PAN', N'Panama', N'U.S. Mission to Panama', 1, 1, 1),
               (10130, N'PNG', N'Papua New Guinea, Solomon Islands & Vanuatu', N'U.S. Mission to Papua New Guinea, Solomon Islands, and Vanuatu', 1, 1, 1),
               (10131, N'PRY', N'Paraguay', N'U.S. Mission to Paraguay', 1, 1, 1),
               (10133, N'PER', N'Peru', N'U.S. Mission to Peru', 1, 1, 1),
               (10134, N'PHL', N'Philippines', N'U.S. Mission to the Philippines', 1, 1, 1),
               (10135, N'POL', N'Poland', N'U.S. Mission to Poland', 1, 1, 1),
               (10136, N'PRT', N'Portugal', N'U.S. Mission to Portugal', 1, 1, 1),
               (10137, N'QAT', N'Qatar', N'U.S. Mission to Qatar', 1, 1, 1),
               (10138, N'ROU', N'Romania', N'U.S. Mission to Romania', 1, 1, 1),
               (10139, N'RUS', N'Russia', N'U.S. Mission to Russia', 1, 1, 1),
               (10140, N'RWA', N'Rwanda', N'U.S. Mission to Rwanda', 1, 1, 1),
               (10143, N'SAU', N'Saudi Arabia', N'U.S. Mission to Saudi Arabia', 1, 1, 1),
               (10144, N'SEN', N'Senegal & Guinea-Bissau', N'U.S. Mission to Senegal and Guinea-Bissau', 1, 1, 1),
               (10145, N'SRB', N'Serbia', N'U.S. Mission to Serbia', 1, 1, 1),
               (10146, N'SLE', N'Sierra Leone', N'U.S. Mission to Sierra Leone', 1, 1, 1),
               (10147, N'SGP', N'Singapore', N'U.S. Mission to Singapore', 1, 1, 1),
               (10148, N'SVK', N'Slovakia', N'U.S. Mission to Slovakia', 1, 1, 1),
               (10149, N'SVN', N'Slovenia', N'U.S. Mission to Slovenia', 1, 1, 1),
               (10152, N'ZAF', N'South Africa', N'U.S. Mission to South Africa', 1, 1, 1),
               (10153, N'ESP', N'Spain & Andorra', N'U.S. Mission to Spain and Andorra', 1, 1, 1),
               (10154, N'LKA', N'Sri Lanka & Maldives', N'U.S. Mission to Sri Lanka and Maldives', 1, 1, 1),
               (10155, N'SDN', N'Sudan', N'U.S. Mission to Sudan', 1, 1, 1),
               (10156, N'SUR', N'Suriname', N'U.S. Mission to Suriname', 1, 1, 1),
               (10157, N'SWZ', N'Swaziland', N'U.S. Mission to Swaziland', 1, 1, 1),
               (10158, N'SWE', N'Sweden', N'U.S. Mission to Sweden', 1, 1, 1),
               (10159, N'CHE', N'Switzerland & Liechtenstein', N'U.S. Mission to Switzerland and Liechtenstein', 1, 1, 1),
               (10160, N'SYR', N'Syria', N'U.S. Mission to Syria', 1, 1, 1),
               (10161, N'AIT', N'AIT', N'American Institute in Taiwan', 1, 1, 1),
               (10162, N'TJK', N'Tajikistan', N'U.S. Mission to Tajikistan', 1, 1, 1),
               (10163, N'TZA', N'Tanzania', N'U.S. Mission to Tanzania', 1, 1, 1),
               (10164, N'THA', N'Thailand', N'U.S. Mission to Thailand', 1, 1, 1),
               (10165, N'TLS', N'Timor-Leste', N'U.S. Mission to Timor-Leste', 1, 1, 1),
               (10166, N'TGO', N'Togo', N'U.S. Mission to Togo', 1, 1, 1),
               (10167, N'TTO', N'Trinidad and Tobago', N'U.S. Mission to Trinidad and Tobago', 1, 1, 1),
               (10168, N'TUN', N'Tunisia', N'U.S. Mission to Tunisia', 1, 1, 1),
               (10169, N'TUR', N'Turkey', N'U.S. Mission to Turkey', 1, 1, 1),
               (10170, N'TKM', N'Turkmenistan', N'U.S. Mission to Turkmenistan', 1, 1, 1),
               (10172, N'UNNY', N'USUN New York', N'U.S. Mission to the United Nations (USUN), New York', 2, 1, 1),
               (10173, N'UNVI', N'USUN Vienna (UNVIE)', N'U.S. Mission to International Organizations in Vienna (UNVIE)', 2, 1, 1),
               (10174, N'UNGE', N'USUN Geneva', N'U.S. Mission to the European Office of the United Nations, Geneva', 2, 1, 1),
               (10176, N'UNRO', N'USUN Rome', N'U.S. Mission to the UN Agencies in Rome (USUN Rome)', 2, 1, 1),
               (10177, N'UNES', N'USUNESCO', N'U.S. Mission to UNESCO (USUNESCO)', 2, 1, 1),
               (10178, N'UGA', N'Uganda', N'U.S. Mission to Uganda', 1, 1, 1),
               (10179, N'UKR', N'Ukraine', N'U.S. Mission to Ukraine', 1, 1, 1),
               (10180, N'ARE', N'United Arab Emirates', N'U.S. Mission to the United Arab Emirates', 1, 1, 1),
               (10181, N'GBR', N'United Kingdom', N'U.S. Mission to the United Kingdom', 1, 1, 1),
               (10182, N'URY', N'Uruguay', N'U.S. Mission to Uruguay', 1, 1, 1),
               (10183, N'OAS', N'USOAS', N'U.S. Permanent Mission to the Organization of American States (USOAS)', 2, 1, 1),
               (10185, N'UZB', N'Uzbekistan', N'U.S. Mission to Uzbekistan', 1, 1, 1),
               (10187, N'VAT', N'Holy See', N'U.S. Mission to the Holy See', 1, 1, 1),
               (10188, N'VEN', N'Venezuela', N'U.S. Mission to Venezuela', 1, 1, 1),
               (10189, N'VNM', N'Vietnam', N'U.S. Mission to Vietnam', 1, 1, 1),
               (10190, N'YEM', N'Yemen', N'U.S. Mission to Yemen', 1, 1, 1),
               (10191, N'ZMB', N'Zambia', N'U.S. Mission to Zambia', 1, 1, 1),
               (10192, N'ZWE', N'Zimbabwe', N'U.S. Mission to Zimbabwe', 1, 1, 1),
               (10193, N'IRN', N'Iran', N'U.S. Mission to Iran', 1, 0, 1),
               (10194, N'SOM', N'Somalia', N'U.S. Mission to Somalia', 1, 1, 1),
               (10195, N'TWN', N'Taiwan', N'U.S. Mission to Taiwan', 1, 0, 1),
               (10196, N'ICAO', N'USICAO', N'U.S. Mission to the International Civil Aviation Organization (USICAO)', 2, 1, 1),
               (10197, N'SSD', N'South Sudan', N'U.S. Mission to South Sudan', 1, 1, 1),
               (10198, N'USASEA', N'USASEAN', N'U.S. Mission to the Association of Southeast Asian Nations (USASEAN)', 2, 1, 1),
               (10199, N'CUW', N'U.S. Mission to the Dutch Caribbean', N'U.S. Mission to the Dutch Caribbean', 1, 1, 1),
               (10200, N'UNEP', N'USUNEP & UN-HABITAT', N'U.S. Mission to UNEP and UN-HABITAT (USUNEP/UN-HABITAT)', 2, 1, 1),
               (10201, N'IAEA', N'USIAEA', N'U.S. Mission to the International Atomic Energy Agency (USIAEA)', 2, 0, 1),
               (10202, N'USCD', N'USCD', N'U.S. Mission to the Conference on Disarmament', 2, 1, 1),
               (10203, N'OPCW', N'USOPCW', N'U.S. Mission to the Organization for the Prohibition of Chemical Weapons (USOPCW)', 2, 1, 1),
               (10204, N'WTO', N'USWTO', N'U.S. Mission to the World Trade Organization (USWTO)', 2, 1, 1)
	END
GO

/*  Turn IDENTITY_INSERT OFF    */
SET IDENTITY_INSERT [location].[Missions] OFF
GO

/*  Set new INDENTIY Starting VALUE */
DBCC CHECKIDENT ('[location].[Missions]', RESEED)
GO
